###############################################etc################################
#                          Don Juan Pablo                                     #
###############################################################################
version: "3.1"
services:

    webserver:
      image: nginx:alpine
      container_name: donjuan-webserver
      working_dir: /application
      volumes:
          - ./application:/application
          - ./cloudengage:/cloudengage
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: donjuan-php-fpm
      working_dir: /application
      volumes:
        - ./application:/application
        - ./cloudengage:/cloudengage
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
        - ./xdebug.log:/log/xdebug.log
      environment: 
         XDEBUG_CONFIG: remote_host=10.0.0.117 remote_enable=1 remote_autostart=1 remote_log=/log/xdebug.log PHP_IDE_CONFIG=PHPSTORM

    mongo:
       restart: always
       image: mongo:3.4
       expose:
        - "27017"
       ports:
         - "27017:27017"
       volumes:
         - mongo:/data/db

    sqldb:
       image: mariadb
       restart: always
       expose:
         - "3306"
       ports:
         - "3306:3306"
       volumes:
         - ./phpdocker/data:/var/lib/mysql:rw
         - ./phpdocker/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
       environment:
         MYSQL_ROOT_PASSWORD: a71dpwro

volumes:
  mongo:
    driver: local
  mysql:
    driver: local
